# Generated by Django 4.2.7 on 2023-12-06 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeronave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('capacidade_passageiros', models.PositiveIntegerField()),
                ('ano_fabricacao', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanhiaAerea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sede', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('passaporte', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('certificado_piloto', models.CharField(max_length=20)),
                ('aeronave_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AeroPro.aeronave')),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data_viagem', models.DateField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroPro.aeronave')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroPro.passageiro')),
            ],
        ),
        migrations.CreateModel(
            name='Comissario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('certificado_comissario', models.CharField(max_length=20)),
                ('aeronave_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AeroPro.aeronave')),
            ],
        ),
        migrations.AddField(
            model_name='aeronave',
            name='companhia_aerea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroPro.companhiaaerea'),
        ),
    ]
