# Generated by Django 4.2.7 on 2023-12-07 01:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AeroPro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passagem',
            old_name='preco',
            new_name='valor',
        ),
        migrations.RemoveField(
            model_name='passagem',
            name='aeronave',
        ),
        migrations.RemoveField(
            model_name='passagem',
            name='status',
        ),
        migrations.AddField(
            model_name='passagem',
            name='data_compra',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='passagem',
            name='descricao',
            field=models.TextField(default='Uma experiência de viagem inesquecível aguarda você, repleta de conforto, serviços excepcionais e destinos fascinantes'),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='data_viagem',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Agendado', 'Agendado'), ('Cancelado', 'Cancelado')], max_length=20)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField(default=datetime.time(12, 0))),
                ('url_imagem', models.URLField(default='https://www.passagenspromo.com.br/blog/wp-content/uploads/2019/09/classes-de-voo-740x415.jpg')),
                ('aeronave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroPro.aeronave')),
                ('passagens', models.ManyToManyField(related_name='voos', to='AeroPro.passagem')),
            ],
        ),
        migrations.AddField(
            model_name='passagem',
            name='voo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AeroPro.voo'),
        ),
    ]
