# Generated by Django 4.2.7 on 2023-12-07 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AeroPro', '0002_rename_preco_passagem_valor_remove_passagem_aeronave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voo',
            name='comissario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AeroPro.comissario'),
        ),
        migrations.AddField(
            model_name='voo',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
        migrations.AlterField(
            model_name='passagem',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
