# Generated by Django 4.2.7 on 2023-12-07 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AeroPro', '0003_voo_comissario_voo_valor_alter_passagem_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='passageiro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AeroPro.passageiro'),
        ),
    ]
