# Generated by Django 4.2.7 on 2023-12-07 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AeroPro', '0004_alter_passagem_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passagem',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AeroPro.passageiro'),
        ),
    ]
