# Generated by Django 4.2.7 on 2023-12-07 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AeroPro', '0005_alter_passagem_passageiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='comissario',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='AeroPro.comissario'),
        ),
    ]
